# Introduction to python

## Variables and assigments

Variables: number, vector, matrix

Assigment statement

In [6]:
x=1

This tells the computer: there is a variable called x and its value is 1

In [7]:
x  # lower case

1

In [8]:
X  # upper case

NameError: name 'X' is not defined

Note that upper and lower-case letters are distinct.

Give your variables meaningful names!

### Variable types

* Integer: 1, 0, -7865
* Float: floating-point variable (includes integers): 3.14159, -3.33 $\cdot 10^{-20}$, 1.
* Complex: 1+2j, -3-5j (i=j)
* String: "This is a string", "3.14159"


Why are there different types? 
- Memory: a complex number takes twice the memory of a float
- Accuracy: integer 1 may be stored as 0.9999999999999

In [9]:
x=1.
y=float(1)
print(x,y) # print x,y

1.0 1.0


In [10]:
z1=1.5+0j
z2=complex(1.5)
print(z1,z2)

(1.5+0j) (1.5+0j)


### Output and input statements


In [11]:
print(x,y,z1)

1.0 1.0 (1.5+0j)


In [12]:
x = input("Enter the value of x:  ")
print("The value of x is",x)

The value of x is 1


### Arithmetic

`x+y` addition

`x-y` subtraction

`x*y` multiplication

`x/y` division

`x**y` raising `x` to the power of `y` 

`x//y` interger part of `x/y` (rounded down to the nearest integer)

`x%y` modulo

In [13]:
x = 14
y = 3
print(x/y, x//y, -x//y)

4.666666666666667 4 -5


In [ ]:
print('x=',x,'y=',y,'--> x%y=',x%y)  # 14 = 3*4 + 2

x= 14 y= 3 --> x%y= 2


In [ ]:
x = 4
y = 2
print(x%y)  # even or odd?

0


In [ ]:
print((x+1)%y)

1


#### Python modifiers and assignments

`x += 1`  add one to `x` $\longrightarrow$ `x = x + 1`

`x -= 4`  subtract 4 from `x`  $\longrightarrow$ `x = x - 4`

`x *= -2.6`  multiply `x` by -2.6 $\longrightarrow$ `x = -2.6*x`

`x /= 5*y`  divide `x` by 5 times `y`   $\longrightarrow$ `x = x / (5*y)`

In [ ]:
x = 7.4
y = 2.3
print(x,y)

7.4 2.3


In [ ]:
x, y = 7.4, 2.3 # this assigns the values of two variables with a single statement
print(x,y)

7.4 2.3


In [ ]:
x, y = 1, 2.5
x += 1     # 1 is an integer
print(x,y)

2 2.5


In [ ]:
x, y = 1, 2.5
x -= 4.   # 4. is a float
print(x,y)

-3.0 2.5


In [ ]:
x, y = 1, 2.5
x /= 5*y
print(x,y)

0.08 2.5


## Functions, packages and modules

For more complicated operations than simple arithmetic (multiplying matrices or making a graph): packages

In [14]:
x = log(10)

NameError: name 'log' is not defined

In [15]:
from math import log   
# This tells the computer to import the logarithm function from the math package
x = log(10)
print(x)

2.302585092994046




**Other functions in math package:**

`log()`   natural logarithm 

`log10()` log base 10

`exp()`   exponential

`sqrt()`  positive square root

`sin()`, `cos()`, `tan()`  trigonometric fuctions: argument in **radians**

...


In [16]:
from math import pi
print(pi**2)

9.869604401089358


In [17]:
from math import log, exp, sin, cos, sqrt, pi, e
print(pi)

3.141592653589793


In [18]:
from math import *  # This imports all functions in a package

Some large packages are split into smaller subpackages: *modules*

A module is refered as `packagename.modulename`

In [19]:
from numpy.linalg import inv  
# This imports the inv function to calculate the inverse of a matrix

#### Build-in functions

Small number of functions which don't come from any package

In [20]:
x = input("Enter the value of x: ")
x = float(x)
print(x)

3.0


## Controlling programs with "if" and "while"

In [ ]:
x = int(input("Enter a whole number no greater than 10."))
if x > 10:                                                     # if condition :
    print("You entered a number greater than 10.")            # tell computer what to do if condition is fulfilled
    print("Let me fix that for you.")                          # --> do all what is indented (any number of spaces)
    x = 5
print("Your number is ",x)                                     # This is out of the if condition

You entered a number greater than 10.
Let me fix that for you.
Your number is  5


More examples:

`if x == 1:`        $\longrightarrow$ Check if $x=1$

`if x > 1:`         $\longrightarrow$ Check if $x>1$

`if x < 1:`        $\longrightarrow$ Check if $x<1$

`if x >= 1:`        $\longrightarrow$ Check if $x\geq1$

`if x <= 1:`        $\longrightarrow$ Check if $x<1$

`if x != 1:`        $\longrightarrow$ Check if $x\neq1$

Combine several conditions:

In [ ]:
if x>10 or x< 1:
    print("Your number is either too big or too small.")

In [ ]:
if x<=10 and x>=1:
    print("Your number is just right.")

Your number is just right.


In [ ]:
if x>10:
    print("Your number is greater than 10.")
elif x>9:                                                        # elif = else if
    print("Your number is ok, but you're cutting it close.")
else:
    print("Your number is fine.")
        

Your number is fine.


In [ ]:
x = int(input("Enter a whole number no greater than 10."))
while x > 10:
    print("Your number is greater than 10. Please try again.")
    x = int(input("Enter a whole number greater than ten."))
print("Your number is ",x)

Your number is greater than 10. Please try again.
Your number is greater than 10. Please try again.
Your number is greater than 10. Please try again.
Your number is greater than 10. Please try again.
Your number is greater than 10. Please try again.
Your number is greater than 10. Please try again.
Your number is greater than 10. Please try again.
Your number is greater than 10. Please try again.
Your number is greater than 10. Please try again.
Your number is  9


## Lists

These are containers.

Elements of a **list** can be numbers, strings or both

Example: `[5, 2, -99]`

In [21]:
r = [ 3, 4, 8, 1, 3, 57 ]
print(r)

[3, 4, 8, 1, 3, 57]


In [22]:
x = 1.0
y = 1.5
z = -2.2
r = [ x, y, z ]
r = [ 2*x, x+y, z/sqrt(x**2+y**2) ]

Elements in a list `r` are denoted `r[0]`, `r[1]`, `r[2]`, ..., `r[-2]`, `r[-1]`

the numbers start from **zero**, not one

Individual elements behave like single variables

In [23]:
from math import sqrt
r = [ 1.0, 1.5, -2.2 ]
length = sqrt( r[0]**2 + r[1]**2 + r[2]**2 )
print(length)

2.8442925306655784


Operations on entire list at once: sum(), max(), min(), len(), map()

In [26]:
r = [ 1.0, 1.5, -2.2 ]
total = sum(r)
print('Total = ', total)
mean = total/len(r)
print('Mean = ', mean)

Total =  0.2999999999999998
Mean =  0.09999999999999994


In [ ]:
from math import log
r = [ 1.0, 1.5, 2.2 ]
logr = list(map(log,r)) #map wendet funktion auf alle elemente der liste an
print(logr)

[0.0, 0.4054651081081644, 0.7884573603642703]


Add and remove elements: append, pop

In [27]:
r = []                     # empty list
r.append(1.0)
r.append(1.5)
r.append(-2.2)
print(r)

[1.0, 1.5, -2.2]


In [28]:
r = [ 1.0, 1.5, -2.2, 2.6 ]
r.pop()
print(r)
r.pop(1)
print(r)

[1.0, 1.5, -2.2]
[1.0, -2.2]


## FOR loops

A `for` loop is a loop that runs through the elements of a list

In [29]:
r = [ 1, 3, 5 ]
for n in r:
    print(n)
    print(2*n)
print("Finished")

1
2
3
6
5
10
Finished


Very useful combine with function `range( )`.

Examples:

`range(5)` gives `[0,1,2,3,4]`

`range(2,8)` gives `[2,3,4,5,6,7]` 
 
`range(2,20,3)` gives `[2,5,8,11,14,17]`

`range(20,2,-3)` gives `[20,17,14,11,8,5]`



In [30]:
r = range(5)
for n in r:
    print("Hello again", n)

Hello again 0
Hello again 1
Hello again 2
Hello again 3
Hello again 4


Examples:

In [31]:
for n in range(1,110):
    print(2**n)

2
4
8
16
32
64
128
256
512
1024
2048
4096
8192
16384
32768
65536
131072
262144
524288
1048576
2097152
4194304
8388608
16777216
33554432
67108864
134217728
268435456
536870912
1073741824
2147483648
4294967296
8589934592
17179869184
34359738368
68719476736
137438953472
274877906944
549755813888
1099511627776
2199023255552
4398046511104
8796093022208
17592186044416
35184372088832
70368744177664
140737488355328
281474976710656
562949953421312
1125899906842624
2251799813685248
4503599627370496
9007199254740992
18014398509481984
36028797018963968
72057594037927936
144115188075855872
288230376151711744
576460752303423488
1152921504606846976
2305843009213693952
4611686018427387904
9223372036854775808
18446744073709551616
36893488147419103232
73786976294838206464
147573952589676412928
295147905179352825856
590295810358705651712
1180591620717411303424
2361183241434822606848
4722366482869645213696
9444732965739290427392
18889465931478580854784
37778931862957161709568
75557863725914323419136
15111

In [32]:
p = 10
q = 2
for n in range(int(p/q)):
    print(n)

0
1
2
3
4


**Example: Emission lines of hydrogen**

Program to calculate the wavelengths of emission lines in the spectrum of the hydrogen atom, based on the Rydberg formula

$$\frac{1}{\lambda} = R \left(\frac{1}{m^2} - \frac{1}{n^2} \right)$$

In [33]:
R = 1.097e-2
for m in range(1,4):
    print("Series for m =",m)
    for n in range(m+1,m+6):
        invlambda = R*(1/m**2-1/n**2) 
        print("n =",n," : ",1/invlambda," nm")

Series for m = 1
n = 2  :  121.5436037678517  nm
n = 3  :  102.55241567912488  nm
n = 4  :  97.23488301428137  nm
n = 5  :  94.95594044363415  nm
n = 6  :  93.76220862091418  nm
Series for m = 2
n = 3  :  656.3354603463993  nm
n = 4  :  486.1744150714068  nm
n = 5  :  434.084299170899  nm
n = 6  :  410.2096627164995  nm
n = 7  :  397.04243897498225  nm
Series for m = 3
n = 4  :  1875.2441724182836  nm
n = 5  :  1281.9051959890612  nm
n = 6  :  1093.8924339106654  nm
n = 7  :  1005.013673655424  nm
n = 8  :  954.6697605038536  nm


## User-defined functions

Python comes with many many functions, but often you need to define your own function.

Example: factorial of *n*: 
$$n! = \prod_{k=1}^n k$$


In [40]:
def factorial(n):
    f = 1.0
    for k in range(1,n+1):
        f *= k
        print(f)
    return f

In [41]:
a = factorial(10)
print('10!=',a)

1.0
2.0
6.0
24.0
120.0
720.0
5040.0
40320.0
362880.0
3628800.0
10!= 3628800.0


**Important**

*Local variables*: any variables created inside the definition of a function exist **only** inside that function. 

In [42]:
print(k)

NameError: name 'k' is not defined

### Arrays

Differences between lists and arrays:

1. Number of elements  fixed

2. All elements: same type

3. Like vectors and matrices: arithmetic with them is possible

4. Faster calculations with arrays



First, create an array: tell the computer the type and number of elements

In [43]:
from numpy import zeros, ones
a = zeros(4,float) 
print('a=',a)
b = ones(2,int)
print('b=',b)

a= [0. 0. 0. 0.]
b= [1 1]


In [44]:
a = zeros([3,4],float)
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [45]:
from numpy import empty
y = empty(4,float)
print(y)

[0. 0. 0. 0.]


In [46]:
from numpy import array
r = [ 1.0, 1.5, -2.2 ]
a = array(r,float)
print('a=',a)

a= [ 1.   1.5 -2.2]


In [47]:
b = array([[1,2,3],[4,5,6]],int)
print('b=',b)
print('First line, second element: ', b[0,1] )
print('Second line, first element: ', b[1,0] )

b= [[1 2 3]
 [4 5 6]]
First line, second element:  2
Second line, first element:  4


### Arithmetic with arrays

In [48]:
from numpy import array
a = array([1,2,3,4],int)

a[0] = a[1] + 1
print( 'a = ', a )

a =  [3 2 3 4]


In [53]:
a = array([1,2,3,4],int)
a[1]

2

In [ ]:
x = a[2]**2 - 2*a[3]  #9-8=1
print( 'x = ', x )

In [ ]:
b = 2*a
print( 'b = ', b )

add or subtract two arrays = add or subtract each element separately

In [ ]:
a = array([1,2,3,4],int)
b = array([2,4,6,8],int)
print(a-b)

same for product!

In [ ]:
print(a*b)

for dot product of two vectors or matrices use: `dot()`

In [ ]:
from numpy import array,dot
a = array([1,2,3,4],int)
b = array([2,4,6,8],int)
print(dot(a,b))

Example:

$\left( \begin{array}{cc}
1 & 3  \\
2 & 4  
\end{array} \right)
\left(\begin{array}{cc}
4 & -2  \\
-3 & 1  
\end{array} \right)
+ 2 \left( \begin{array}{cc}
1 & 2  \\
2 & 1  
\end{array} \right)
=
\left( \begin{array}{cc}
-3 & 5  \\
0 & 2  
\end{array} \right)
$

In [ ]:
a = array([[1,3],[2,4]],int)
b = array([[4,-2],[-3,1]],int)
c = array([[1,2],[2,1]],int)
print(dot(a,b)+2*c)

There are many functions in the `numpy` package to perform calculations with array. Examples: `a.size`, `a.shape`, ...

**Warning**

In [ ]:
from numpy import array 
a = array([1,1],int) 
b = a
a[0] = 2
print(a) 
print(b)

`b` is not a copy of `a` 

`b` is a new name for `a`, both refere to the same array of numbers

In [ ]:
from numpy import array, copy 
a = array([1,1],int) 
b = copy(a)
a[0] = 2
print(a)
print(b)

### Slicing

In [ ]:
r = [ 1, 3, 5, 7, 9, 11, 13, 15 ]
print('r[2:5]=',r[2:5])
print('r[5:]=',r[5:])
print('r[:3]=',r[:3])
print('r[:]=',r[:])

### Reading an array from a file

In [ ]:
from numpy import loadtxt
a = loadtxt("values.txt")
print(a)

### .h5 files

An HDF5 file is a container for two kinds of objects: datasets, which are array-like collections of data, and groups, which are folder-like containers that hold datasets and other groups. 

Groups work like dictionaries, and datasets work like NumPy arrays

In [ ]:
import h5py

f=h5py.File('file.h5','r') #open the file

f_keys=f.keys() #obtain the most external datasets and groups names, say one dataset named key1 and one group named key2

dataset1=f['key1'] #store in the variable dataset1 the content of dataset key1 (which is an array)
group1=f['key2'] #store in the variable group1 the content of group key2 (which is a dictionary)

fg_keys=f['key2'].keys() #obtain the names of groups and datasets in group key2, say only one dataset named key3

dataset2=f['key2']['key3'] #key

f.close() #always close the file after you have done the reading!